apiVersion: v1
kind: Secret
metadata:
  name: mongoexpress-secret
type: Opaque
data:
  mongoExpress-root-username: dXNlcm5hbWU= # Base64-encoded 
  mongoExpress-root-password: cGFzc3dvcmQ= # Base64-encoded 
  mongoExpress-root-server: ##


